nameOverride: ""
replicaCount: 2

image:
  repository: ghcr.io/ryanmerlin/edgeplane
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  EP_BASE_URL: https://edgeplane.internal
  EP_TOKEN: placeholder-token
  POSTGRES_HOST: placeholder-postgres
  POSTGRES_USER: mc_admin
  POSTGRES_PASSWORD: placeholder
  MC_OBJECT_STORAGE_ENDPOINT: http://minio.edgeplane.svc.cluster.local
  MC_OBJECT_STORAGE_BUCKET: edgeplane
  MC_OBJECT_STORAGE_ACCESS_KEY: minio
  MC_OBJECT_STORAGE_ACCESS_SECRET: minio123

secrets: {}

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
