/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the authenticated caller's identity. */
        get: operations["auth_me_stub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/governance/policy/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the currently active governance policy, seeding the default if none exists. */
        get: operations["governance_active_stub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — returns `200 ok` with version string. No auth required. */
        get: operations["health_stub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Response emitted by `GET /api/governance/policy/active`. */
        GovernancePolicyResponse: {
            /** @description Human-readable change note. */
            change_note: string;
            /** @description ISO-8601 UTC timestamp of record creation. */
            created_at: string;
            /** @description Subject that created this policy record. */
            created_by: string;
            /**
             * Format: int32
             * @description Database row ID.
             */
            id: number;
            /** @description Parsed governance policy object. */
            policy: unknown;
            /** @description ISO-8601 UTC timestamp of publication; `null` for drafts. */
            published_at?: string | null;
            /** @description Subject that published this policy (empty string for drafts). */
            published_by: string;
            /** @description Policy lifecycle state: `"active"`, `"draft"`, or `"archived"`. */
            state: string;
            /** @description ISO-8601 UTC timestamp of last update. */
            updated_at: string;
            /**
             * Format: int32
             * @description Monotonically increasing version number.
             */
            version: number;
        };
        /** @description Response emitted by `GET /api/health`. */
        HealthResponse: {
            /** @description Always `"ok"` when the server is reachable. */
            status: string;
            /** @description Crate version string (e.g. `"0.12.0"`). */
            version: string;
        };
        MeResponse: {
            /** @description Authentication mechanism used: "session", "service_account", or "oidc_jwt". */
            auth_type: string;
            /**
             * Format: int32
             * @description Session database ID — present for session tokens, absent for service account tokens.
             */
            session_id?: number | null;
            /** @description The authenticated principal's subject identifier (e.g. OIDC sub or service account name). */
            subject: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_me_stub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    governance_active_stub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active governance policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernancePolicyResponse"];
                };
            };
            /** @description Default policy seeded (first call on empty DB) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovernancePolicyResponse"];
                };
            };
            /** @description Missing or invalid token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health_stub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
