[package]
name = "mcd-packs"
version.workspace = true
edition = "2021"

[dependencies]
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tracing = { workspace = true }
mcd-sandbox = { path = "../mcd-sandbox" }
mcd-secrets = { path = "../mcd-secrets" }
