apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgeplane.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "edgeplane.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "edgeplane.fullname" . }}
    spec:
      containers:
        - name: edgeplane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "edgeplane.fullname" . }}-config
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "edgeplane.fullname" . }}-secrets
            {{- end }}
          ports:
            - containerPort: 8008
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8008
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8008
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
