apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edgeplane.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "edgeplane.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "edgeplane.fullname" . }}
    spec:
      containers:
        - name: edgeplane
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "edgeplane.fullname" . }}-config
            {{- if .Values.secrets }}
            - secretRef:
                name: {{ include "edgeplane.fullname" . }}-secrets
            {{- end }}
          ports:
            - containerPort: 8008
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8008
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8008
