[package]
name = "edgeplaned-secrets"
version.workspace = true
edition = "2021"

[dependencies]
async-trait = "0.1"
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
urlencoding = "2"
uuid = { workspace = true }
once_cell = "1"
zeroize = { version = "1.8.2", features = ["zeroize_derive"] }

[dev-dependencies]
tokio = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
keyring = { workspace = true }
