[package]
name = "edgeplaned-sync"
version.workspace = true
edition = "2021"

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
edgeplaned-paths = { path = "../../../edgeplaned-paths" }

[dev-dependencies]
tempfile = "3"
