/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NodesRouteImport } from './routes/nodes'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NodesIndexRouteImport } from './routes/nodes.index'
import { Route as DomainsIndexRouteImport } from './routes/domains.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NodesNodeIdRouteImport } from './routes/nodes.$nodeId'
import { Route as DomainsDomainIdRouteImport } from './routes/domains.$domainId'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as DomainsDomainIdMissionsMissionIdRouteImport } from './routes/domains.$domainId.missions.$missionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesRoute = NodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NodesIndexRoute = NodesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NodesRoute,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DomainsRoute,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NodesNodeIdRoute = NodesNodeIdRouteImport.update({
  id: '/$nodeId',
  path: '/$nodeId',
  getParentRoute: () => NodesRoute,
} as any)
const DomainsDomainIdRoute = DomainsDomainIdRouteImport.update({
  id: '/$domainId',
  path: '/$domainId',
  getParentRoute: () => DomainsRoute,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => AgentsRoute,
} as any)
const DomainsDomainIdMissionsMissionIdRoute =
  DomainsDomainIdMissionsMissionIdRouteImport.update({
    id: '/missions/$missionId',
    path: '/missions/$missionId',
    getParentRoute: () => DomainsDomainIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/domains': typeof DomainsRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/feed': typeof FeedRoute
  '/governance': typeof GovernanceRoute
  '/matrix': typeof MatrixRoute
  '/nodes': typeof NodesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/domains/$domainId': typeof DomainsDomainIdRouteWithChildren
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/domains/$domainId/missions/$missionId': typeof DomainsDomainIdMissionsMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explorer': typeof ExplorerRoute
  '/feed': typeof FeedRoute
  '/governance': typeof GovernanceRoute
  '/matrix': typeof MatrixRoute
  '/onboarding': typeof OnboardingRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/domains/$domainId': typeof DomainsDomainIdRouteWithChildren
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/admin': typeof AdminIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/nodes': typeof NodesIndexRoute
  '/domains/$domainId/missions/$missionId': typeof DomainsDomainIdMissionsMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agents': typeof AgentsRouteWithChildren
  '/domains': typeof DomainsRouteWithChildren
  '/explorer': typeof ExplorerRoute
  '/feed': typeof FeedRoute
  '/governance': typeof GovernanceRoute
  '/matrix': typeof MatrixRoute
  '/nodes': typeof NodesRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/domains/$domainId': typeof DomainsDomainIdRouteWithChildren
  '/nodes/$nodeId': typeof NodesNodeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/nodes/': typeof NodesIndexRoute
  '/domains/$domainId/missions/$missionId': typeof DomainsDomainIdMissionsMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agents'
    | '/domains'
    | '/explorer'
    | '/feed'
    | '/governance'
    | '/matrix'
    | '/nodes'
    | '/onboarding'
    | '/agents/$agentId'
    | '/domains/$domainId'
    | '/nodes/$nodeId'
    | '/admin/'
    | '/agents/'
    | '/domains/'
    | '/nodes/'
    | '/domains/$domainId/missions/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explorer'
    | '/feed'
    | '/governance'
    | '/matrix'
    | '/onboarding'
    | '/agents/$agentId'
    | '/domains/$domainId'
    | '/nodes/$nodeId'
    | '/admin'
    | '/agents'
    | '/domains'
    | '/nodes'
    | '/domains/$domainId/missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agents'
    | '/domains'
    | '/explorer'
    | '/feed'
    | '/governance'
    | '/matrix'
    | '/nodes'
    | '/onboarding'
    | '/agents/$agentId'
    | '/domains/$domainId'
    | '/nodes/$nodeId'
    | '/admin/'
    | '/agents/'
    | '/domains/'
    | '/nodes/'
    | '/domains/$domainId/missions/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentsRoute: typeof AgentsRouteWithChildren
  DomainsRoute: typeof DomainsRouteWithChildren
  ExplorerRoute: typeof ExplorerRoute
  FeedRoute: typeof FeedRoute
  GovernanceRoute: typeof GovernanceRoute
  MatrixRoute: typeof MatrixRoute
  NodesRoute: typeof NodesRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes': {
      id: '/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof NodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodes/': {
      id: '/nodes/'
      path: '/'
      fullPath: '/nodes/'
      preLoaderRoute: typeof NodesIndexRouteImport
      parentRoute: typeof NodesRoute
    }
    '/domains/': {
      id: '/domains/'
      path: '/'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/agents/': {
      id: '/agents/'
      path: '/'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/nodes/$nodeId': {
      id: '/nodes/$nodeId'
      path: '/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof NodesNodeIdRouteImport
      parentRoute: typeof NodesRoute
    }
    '/domains/$domainId': {
      id: '/domains/$domainId'
      path: '/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof DomainsDomainIdRouteImport
      parentRoute: typeof DomainsRoute
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof AgentsRoute
    }
    '/domains/$domainId/missions/$missionId': {
      id: '/domains/$domainId/missions/$missionId'
      path: '/missions/$missionId'
      fullPath: '/domains/$domainId/missions/$missionId'
      preLoaderRoute: typeof DomainsDomainIdMissionsMissionIdRouteImport
      parentRoute: typeof DomainsDomainIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentsRouteChildren {
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
}

const AgentsRouteChildren: AgentsRouteChildren = {
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  AgentsIndexRoute: AgentsIndexRoute,
}

const AgentsRouteWithChildren =
  AgentsRoute._addFileChildren(AgentsRouteChildren)

interface DomainsDomainIdRouteChildren {
  DomainsDomainIdMissionsMissionIdRoute: typeof DomainsDomainIdMissionsMissionIdRoute
}

const DomainsDomainIdRouteChildren: DomainsDomainIdRouteChildren = {
  DomainsDomainIdMissionsMissionIdRoute: DomainsDomainIdMissionsMissionIdRoute,
}

const DomainsDomainIdRouteWithChildren = DomainsDomainIdRoute._addFileChildren(
  DomainsDomainIdRouteChildren,
)

interface DomainsRouteChildren {
  DomainsDomainIdRoute: typeof DomainsDomainIdRouteWithChildren
  DomainsIndexRoute: typeof DomainsIndexRoute
}

const DomainsRouteChildren: DomainsRouteChildren = {
  DomainsDomainIdRoute: DomainsDomainIdRouteWithChildren,
  DomainsIndexRoute: DomainsIndexRoute,
}

const DomainsRouteWithChildren =
  DomainsRoute._addFileChildren(DomainsRouteChildren)

interface NodesRouteChildren {
  NodesNodeIdRoute: typeof NodesNodeIdRoute
  NodesIndexRoute: typeof NodesIndexRoute
}

const NodesRouteChildren: NodesRouteChildren = {
  NodesNodeIdRoute: NodesNodeIdRoute,
  NodesIndexRoute: NodesIndexRoute,
}

const NodesRouteWithChildren = NodesRoute._addFileChildren(NodesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentsRoute: AgentsRouteWithChildren,
  DomainsRoute: DomainsRouteWithChildren,
  ExplorerRoute: ExplorerRoute,
  FeedRoute: FeedRoute,
  GovernanceRoute: GovernanceRoute,
  MatrixRoute: MatrixRoute,
  NodesRoute: NodesRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
